language: objective-c
osx_image: xcode7.1
script:
  - xctool -workspace RingCentral.xcworkspace -scheme RingCentralTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES


after_success:
  - bash <(curl -s https://codecov.io/bash)
