language: swift
osx_image: xcode7.1


before_install:
  - sudo gem install bundler --no-ri --no-rdoc
  - sudo bundle install
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - xcodebuild -scheme RingCentral -workspace RingCentral.xcworkspace -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)
